using UnityEditor.Profiling;
using UnityEngine;

public class EnemyBase : MonoBehaviour
{
    //-----댷벍-----
    private Vector3 pos;
    private int num = 1;
    [SerializeField] private float speed = 3f;

    [SerializeField] private Data data;     //밎ID
    void Start()
    {
        
    }

    void Update()
    {
        pos = transform.position;
        transform.Translate(transform.right * Time.deltaTime * speed * num);

        if (pos.x >11)
        {
            num = -1;
        }
        else if (pos.x < -7.5)
        {
            num = 1;
        }
    }

    //-----ID빶궸룉뿚-----
    public void SelectID()
    {
        //ID귩롦벦
        int enemyID = data.GetID();

        switch (enemyID)
        {
            //ID1궶귞
            case 1:
                Debug.Log("ID1");
                break;
            //ID2궶귞
            case 2:
                Debug.Log("ID2");
                break;
            default:
                Debug.Log("궩궻뫜");
                break;
        }
    }
}
